name: devgram
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  device_info_plus: ^9.0.0
  image_picker: ^1.0.7
  get_it: ^8.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

